controller_list:
  - name: fake_left_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
initial:  # Define initial robot poses.
#  - group: left_manipulator
#    pose: home

  []