controller_list:
  - name: fake_right_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
initial:  # Define initial robot poses.
#  - group: right_manipulator
#    pose: home

  []